### PR TITLE
Day 2: Idiomatic num_divisors() implementation

### PR DESCRIPTION
**Pull request by xmartinez**
Provide an alternative implementation for num_divisors that:

- uses `map` and `product` from the `Iterator` trait (instead of
  `fold`),
- uses `map` and `ok` from the `Result` trait (instead of pattern
  matching on `Ok` and `Err`).

Also, update the included line ranges in day2.md accordingly (some of
them were outdated).

### CODE REVIEW

**Comment by xmartinez** [comment]
I am not 100% sure that the proposed change is actually very idiomatic (I am still learning Rust), but I find the introduction of the new methods (map, product, ok) useful for learning the `Result` and `Iterator` traits.

BTW, thanks a lot for making this docs! I am finding them very helpful while getting familiar with Rust.

**Comment by xmartinez** [comment]
The [Travis CI failure](https://travis-ci.org/zsiciarz/24daysofrust/builds/305906853) is unrelated to this pull request. It is timing out in the `day20` program when fetching an external URL (http://pokeapi.co/api/v2/pokemon/111).

**Comment by xmartinez** [comment]
Closed/reopened PR to trigger CI builds again.

**Comment by zsiciarz** [comment]
Awesome, thanks! I wrote this part before 1.0, when `product()` was in an unstable `MultiplicativeIterator` trait and hence I used `fold()` here. But you're absolutely right about `product()` being idiomatic Rust today.

**Pull request merged**
